# Generated by Django 3.1.1 on 2020-11-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='credito',
            field=models.FloatField(default=0, verbose_name='Credito'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='DISPONIBLE', max_length=50, verbose_name='Estado'),
        ),
    ]
