# Generated by Django 3.1.1 on 2020-11-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201103_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Imagen de perfil'),
        ),
    ]
